name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary selenium
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb chromedriver

      - name: Start local server
        run: |
          cd src
          python3 -m http.server 8000 &
          cd ..
          sleep 10

      - name: Run Robot Framework tests
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 &
          robot Testes/
