name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary selenium

      - name: Start your app
        run: |
          # Exemplo: suba seu app local (substitua pelo seu comando real)
          # Ex: npm install && npm run dev
          # Ou: python app.py &
          echo "Suba seu servidor aqui"

      - name: Start Xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 &
        shell: bash

      - name: Run tests
        env:
          DISPLAY: :99
        run: |
          robot Testes/
