name: Robot Framework Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and Chrome
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-seleniumlibrary selenium
          sudo apt-get update
          sudo apt-get install -y wget unzip google-chrome-stable xvfb

      - name: Install matching Chromedriver
        run: |
          # Detect Chrome version installed
          CHROME_VERSION=$(google-chrome-stable --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"

          # Download matching chromedriver from Chrome for Testing
          wget -O /tmp/chromedriver.zip \
            "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chromedriver-linux64.zip"

          unzip /tmp/chromedriver.zip -d /tmp/
          sudo mv /tmp/chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          chromedriver --version

      - name: Start local server
        run: |
          cd src
          python3 -m http.server 8000 &
          cd ..
          sleep 10

      - name: Run Robot Framework tests
        env:
          DISPLAY: :99
        run: |
          Xvfb :99 &
          robot Robot/Testes/
